# Generated by Django 5.2.3 on 2025-06-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=75)),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('included_in_these_chats', models.JSONField(default=list)),
            ],
        ),
    ]
