# Generated by Django 5.2.3 on 2025-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.JSONField(default=list)),
                ('is_group_chat', models.BooleanField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameModel(
            old_name='dbModel',
            new_name='userDB',
        ),
    ]
